default_language_version:
  python: python3.9

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: fix-encoding-pragma
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
- repo: local
  hooks:
  - id: black
    name: black
    entry: poetry run black
    language: system
    types: [python]
  - id: isort
    name: isort
    entry: poetry run isort
    language: system
    types: [python]
  - id: flake8
    name: flake8
    entry: flake8
    language: system
    types: [python]
  - id: mypy
    name: mypy
    entry: poetry run mypy
    args: ['--ignore-missing-imports']
    language: system
    types: [python]
