[tool.poetry]
name = "project-template"
version = "0.1.0"
description = "A cookiecutter template implementing as many best practices as possible"
license = "GPL-3-or-later"
authors = ["rbpatt2019 <rb.patterson.cross@gmail.com>"]
homepage = "https://github.com/rbpatt2019/project-template"
repository = "https://github.com/rbpatt2019/project-template"
keywords = ["cookiecutter"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
pytest-clarity = "^0.3.0-alpha.0"
pytest-sugar = "^0.9.4"
pytest-mock = "^3.4.0"
six = "^1.15.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
